### ISSUE TITLE
To support -A (all permissions) -r (--reload) and all deno args.

### ISSUE THREAD

**Issue by fakoua** [denorg/dpx#2]
Hi,
Currently, --allow-net works fine, but -A does not work (instead of --allow-net --allow-env --allow-read --allow-write) ...
Also --reload works fine while -r does not.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @fakoua! You’re right, I check for double hyphens, which is a hack. I’ll refactor the code today and make sure this is fixed!

**Comment by AnandChowdhary** [comment]
I've deployed a fix that should work for you.
