### ISSUE TITLE
 add dpx inside Trex

### ISSUE THREAD

**Issue by buttercubz** [denorg/dpx#3]
I am making a dependency manager for deno based on import_map, it also has the functionality to install tools like [commands](https://github.com/buttercubz/Commands) or [velociraptor](https://github.com/umbopepato/velociraptor)

is there a problem with adding dpx to the list of tools that can be installed?

this is my tool [Trex](https://github.com/crewdevio/Trex)

**Comment by AnandChowdhary** [comment]
Would love to have it!

**Comment by AnandChowdhary** [comment]
If you want to execute `dpx` directly, perhaps the best way to do it is:

```
deno run --allow-read --allow-run https://deno.land/x/dpx/cli.ts <flags> <packageName> <arguments>
```

So, if you want to have a command like `trex dpx <flags> <packageName> <arguments>` just executing the above line would be enough.

**Comment by buttercubz** [comment]
Thank you very much, the ecosystem for deno is not comfortable for js node programmers, with these tools it would be easier
