### ISSUE TITLE
feat: To Support https://nest.land/

### ISSUE THREAD

**Issue by fakoua** [denorg/dpx#5]
I would suggest to support https://nest.land packages, and maybe other repositories, and the default is deno.land

**Comment by AnandChowdhary** [comment]
Good idea! I think we can have a syntax similar to:

```bash
dpx online --allow-net # deno.land by default
```

```bash
dpx --registry https://nest.land online --allow-net # nest.land
```

And the `registry` flag can be arbitrary to any URL. What do you think?

**Comment by fakoua** [comment]
Hi @AnandChowdhary ,
Yes I think it would be great.  at first i tried to push a PR with hardcoded repos (familiar repos), for example:

```
dpx --registry nest online --args
```
or may be

```
dpx rest/online --args
```
To simplify the UX, so I think if we can merge the 2 solutions it would be great.

And in the help you can enumerate the supported repos and obviously the user can use --registry https://whatever.x for generic solution.

**Comment by AnandChowdhary** [comment]
Sounds good, I think the combined approach works best with certain hardcoded registries.

**Comment by AnandChowdhary** [comment]
Closing this because of the great work in #6!

**Comment by t8** [comment]
Feel free to put denorg modules (such as `dpx`) on nest.land too! Thanks so much for supporting our registry in `dpx` 😄
